services:
    mysql:
        image: mysql:8.0
        container_name: mysql_db
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        ports:
            - '3306:3306'
        volumes:
            - database:/var/lib/mysql
        networks:
            - app-network

networks:
    app-network:
        external: true

volumes:
    database:
